name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: [ vm ]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) |
            docker push static/$GITHUB_REPOSITORY:${{github.run_number}}
