name: Static Web Github Action
on:
  push:
    branches: [master]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: install docker 
      uses: docker-practice/actions-setup-docker@master

 
  builds:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Docker Images
      run: |
             echo "$PWD"
             ls -la
             docker build . --file Dockerfile --tag app:${{github.run_number}}
      
         
