name: Static Web Github Action
on:
  push:
    branches: [master]
    
# concurrency:
#   group: ${{ github.workflow }} 
#   cancel-in-progress: true
  
jobs:
  
  builds:
    runs-on: [self-hosted,demorunner]
    steps:
    - name: build
      uses: actions/checkout@v2

    - name: Docker Images
      run: |
             echo "$PWD"
             ls -la
             docker build . --file Dockerfile --tag app:${{github.run_number}}
      
         
