name: Static Web Github Action
on:
  push:
    branches: [master]
    
concurrency:
  group: ${{ github.workflow }} 
  cancel-in-progress: true
  
jobs:
  
  build:
  
    runs-on: ubuntu-latest
    steps:
    - name: install docker 
      uses: docker-practice/actions-setup-docker@master

  builds:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: build
      uses: actions/checkout@v2

    - name: Docker Images
      run: |
             echo "$PWD"
             ls -la
             docker build . --file Dockerfile --tag app:${{github.run_number}}
      
         
