name: Static Web Github Action
on:
  push:
    branches: master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install docker 
    - uses: docker-practice/actions-setup-docker@master
    - run: |
          set +x
          docker --version
          docker build . --file Dockerfile app:${{github.run_number}}
         
